---
- name: get hosts facts
  hosts: all
  gather_facts: yes

- name: test websit
  hosts: centos
  gather_facts: no
  vars:
    code_repo: git@github.com:BoxingP/website-test-scripts.git
    code_repo_key: ~/.ssh/id_rsa_github_boxingp
    code_path: /tmp/website_test/
    virtualenv: '{{ hostvars[inventory_hostname].ansible_env.HOME }}/.virtualenvs/website_test-env'
  vars_files:
    - vars/website_login_credential.yaml
  tasks:
    - name: init server environment
      include_role:
        name: init_server_environment
    - name: init workspace
      import_tasks: tasks/init_workspace.yaml
    - name: create python environment
      include_role:
        name: create_python_environment
    - name: install chromedriver
      import_tasks: tasks/install_chrome_chromedriver.yaml
    - name: run testing
      block:
        - name: test website
          import_tasks: tasks/test_website.yaml
          vars:
            test_script: homepage_login_logout
      vars:
        ansible_python_interpreter: '{{ virtualenv }}/bin/python3'
      environment:
        PATH: '{{ virtualenv }}/bin:{{ hostvars[inventory_hostname].ansible_env.PATH }}'